class CfgPatches
{
	class KOTHWaves
	{
		units[] =
		{
			"KOTHWavesSmokeProxy",
			"KOTHWavesTerritoryFlag",
			"KOTHWavesRewardCrate"
		};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] =
		{
			"DZ_Data",
			"DZ_Scripts",
			"DZ_Characters_Zombies",
			"DZ_Gear_Containers",
			"DZ_Gear_Camping",
			"DZ_Gear_Tools"
		};
	};
};

class CfgMods
{
	class KOTHWaves
	{
		dir = "KOTHWaves";
		picture = "";
		action = "";
		hideName = 0;
		hidePicture = 1;
		name = "KOTH Waves";
		logoSmall = "";
		logo = "";
		logoOver = "";
		tooltip = "King of the Hill with configurable zombie waves";
		overview = "Standalone server-side KOTH event with configurable zombie waves and rewards.";
		credits = "";
		author = "Server Owner";
		authorID = "0";
		version = "1.0";
		extra = 0;
		type = "mod";
		
		dependencies[] =
		{
			"World",
			"Mission"
		};
		
		class defs
		{
			class worldScriptModule
			{
				value = "";
				files[] =
				{
					"KOTHWaves/Scripts/4_World"
				};
			};
			
			class missionScriptModule
			{
				value = "";
				files[] =
				{
					"KOTHWaves/Scripts/5_Mission"
				};
			};
		};
	};
};

class CfgVehicles
{
	class WoodenStick;
	class KOTHWavesSmokeProxy: WoodenStick
	{
		scope = 2;
		displayName = " ";
		descriptionShort = "";
		itemSize[] = {1, 1};
		itemsCargoSize[] = {0, 0};
		canBeSplit = 0;
		varQuantityDestroyOnMin = 0;
		quantityBar = 0;
		rotationFlags = 17;
	};
	
	class TerritoryFlag;
	class KOTHWavesTerritoryFlag: TerritoryFlag
	{
		scope = 2;
		displayName = "KOTH Territory Flag";
		descriptionShort = "Drapeau d'evenement KOTH — non revendicable, sans territoire joueur.";
	};
	
	class WoodenCrate;
	class KOTHWavesRewardCrate: WoodenCrate
	{
		scope = 2;
		displayName = "KOTH Reward Crate";
		descriptionShort = "Reward crate generated by KOTH Waves. Loot can be taken, but the crate cannot be moved.";
		
		class Cargo
		{
			itemsCargoSize[] = {10, 100};
			openable = 0;
			allowOwnedCargoManipulation = 1;
		};
	};
};
